title: Risdan Kristori # your name (or website title) here
logo: "/images/risdan.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Data Enthusiast (Python, R, SQL & Tableau)<br>
  <a href="https://www.linkedin.com/in/risdan-kristori-02023211b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
